import { blueGrey, cyan, red } from 'material-ui-colors'
import type { MD3Theme } from 'react-native-paper'
import { MD3DarkTheme as DefaultTheme } from 'react-native-paper'

export const darkTheme: MD3Theme = {
  ...DefaultTheme,
  dark: true,
  mode: 'exact',
  roundness: 4,
  colors: {
    ...DefaultTheme.colors,
    primary: cyan[500],
    primaryContainer: '#5f5',
    secondary: '#5f5',
    secondaryContainer: '#5f5',
    tertiary: '#5f5',
    tertiaryContainer: '#5f5',
    surface: '#5f5',
    surfaceVariant: '#5f5',
    surfaceDisabled: '#5f5',
    background: blueGrey[700],
    error: red[400],
    errorContainer: '#5f5',
    onPrimary: cyan[50],
    onPrimaryContainer: '#5f5',
    onSecondary: '#5f5',
    onSecondaryContainer: '#5f5',
    onTertiary: '#5f5',
    onTertiaryContainer: '#5f5',
    onSurface: blueGrey[100],
    onSurfaceVariant: '#5f5',
    onSurfaceDisabled: '#5f5',
    onError: red[50],
    onErrorContainer: '#5f5',
    onBackground: '#5f5',
    outline: '#5f5',
    outlineVariant: '#5f5',
    inverseSurface: '#5f5',
    inverseOnSurface: '#5f5',
    inversePrimary: '#5f5',
    shadow: '#5f5',
    scrim: '#5f5',
    backdrop: '#5f5',
  },
}
