import { blueGrey, cyan, red } from 'material-ui-colors'
import type { MD3Theme } from 'react-native-paper'
import { MD3DarkTheme as DefaultTheme } from 'react-native-paper'

export const darkTheme: MD3Theme = {
  ...DefaultTheme,
  dark: true,
  mode: 'exact',
  roundness: 4,
  colors: {
    ...DefaultTheme.colors,
    primary: cyan[500],
    primaryContainer: '#ff5',
    secondary: '#ff5',
    secondaryContainer: '#ff5',
    tertiary: '#ff5',
    tertiaryContainer: '#5f5',
    surface: '#ff5',
    surfaceVariant: '#ff5',
    surfaceDisabled: '#ff5',
    background: blueGrey[700],
    error: red[400],
    errorContainer: red[400],
    onPrimary: cyan[50],
    onPrimaryContainer: '#5f5',
    onSecondary: '#5f5',
    onSecondaryContainer: '#5f5',
    onTertiary: '#ff5',
    onTertiaryContainer: '#ff5',
    onSurface: blueGrey[100],
    onSurfaceVariant: cyan[200],
    onSurfaceDisabled: blueGrey[200],
    onError: red[50],
    onErrorContainer: red[50],
    onBackground: '#5f5',
    outline: cyan[200],
    outlineVariant: blueGrey[600],
    inverseSurface: '#5f5',
    inverseOnSurface: '#5f5',
    inversePrimary: '#5f5',
    shadow: '#5f5',
    scrim: '#5f5',
    backdrop: '#5f5',
  },
}
